# Generated by Django 4.1.7 on 2023-04-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pubish_date']},
        ),
    ]
